### PR TITLE
Remote + system variant

### PR DESCRIPTION
**Pull request by proninyaroslav**
It would be nice and convenient to have a remote system backup script without editing the `rsync-incremental-backup-remote` file constantly. I have combined both options in one file.

### CODE REVIEW

**Comment by proninyaroslav** [comment]
The only moment with which I encountered is: backup files don't save information about owner and group. I found two solutions:
1. Logged SSH as root and apply `-o` and `-g` options for rsync. But for this, it's necessary for the root that insensitive in many situations.
2. Use the `--fake-super` option, which saves this information in extended attributes (if the filesystem supports it). But it seems that it doesn't work, or maybe I misinterpret this option.

@pedroetb 
What do you think about this?

**Comment by pedroetb** [comment]
Hi @proninyaroslav, I will check this soon, thanks!

**Comment by proninyaroslav** [comment]
@pedroetb 
Thank you! I tried to execute this command from root, but it doesn't restore xattrs that the `-M--fake-super` option saves during the backup, although they are there. In other words, if the files are owned by UID 1000, then this command saves them as root:

`sudo rsync -av --fake-super user@remote::src dest`

**Comment by proninyaroslav** [comment]
I managed to restore xattrs on the client machine, as it turned out to we need to specify `-M--fake-super`, not `--fake-super` during restoration:

`sudo rsync -av -M--fake-super rsync-server::src dest`

**Comment by proninyaroslav** [comment]
@pedroetb  Can you review this?

**Comment by pedroetb** [comment]
Hi @proninyaroslav, I will try to review it this week, thanks for reminder!

**Comment by pedroetb** [comment]
Ok, I understand that you need a system backup with remote capabilities, instead of customizing the existing remote script with desired parameters.

Sound interesting to me, but I need to check `-M--fake-super` in deep before merging, to fully understand it. In the meantime, can you confirm if it is working for you?

Thanks!

**Comment by proninyaroslav** [comment]
@pedroetb 
Yes, it works.

**Comment by pedroetb** [comment]
Ok, I have tested it myself and everything works as described, thanks!

I will PR some minor changes before merging, but it's working great.

**Comment by proninyaroslav** [comment]
Thank you for merging. Why did you add `--no-W` instead of `-W` in the final version?

**Comment by pedroetb** [comment]
Since backup is going to remote target, I think is better to use delta transfer (like in remote script).

**Comment by Megver83** [comment]
just wanted to point out that it does not have the execution bit

````
diff --git a/rsync-incremental-backup-system-remote b/rsync-incremental-backup-system-remote
old mode 100644
new mode 100755
````

**Comment by pedroetb** [comment]
> Are there any risks of using it? For example, loss of file integrity?

@proninyaroslav I don't think so, this option is used in (generic) remote script and no problems have been reported.

@Megver83 good catch! I didn't notice before, thanks!

**Pull request merged**
